project:
  type: website

website:
  title: "MichWebStudies"    
  navbar:    
    left:
    - text: "Home"
      file: index.qmd 
    - text: "React"
      file: react.qmd
    - text: "Mindset"
      file: mindset.qmd
    - text: "Linux"
      file: linux.qmd
    - text: "DeVops"
      file: devops.qmd
    - text: "About"
      file: about.qmd 

    - sidebar:java
  sidebar:
  - id: java
    title: "Java"
    style: "docked"
    background: light
    collapse-level: 2
    contents: 
      # navigation items
      - java.qmd
      - JavaProject.qmd

  

  - id: react
    title: "React"
    contents: 
      # navigation items
      - react.qmd
      - JavaProject.qmd    
      


    

 
   

format:
  html:
    theme: vapors
    css: styles.css
    toc: true
    
